services:
  - type: web
    name: techship-app
    env: python
    pythonVersion: "3.12.5"
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run techship_dash2.py
    autoDeploy: true
